alias r='. ranger'
alias t='transset-df'
alias f='fastfetch'
alias b='btop'
alias fb='firefox&'
alias c='clear'
alias u='unimatrix -a -b -f -c cyan -s 91 -l aAsS'
alias j3='journalctl -b -p 3'
alias j4='journalctl -b -p 4'
alias pk='pacman -Qe'
alias pkn='pacman -Qe | wc -l'
alias jf='journalctl -f'
alias or='pacman -Qtdq'
alias nv='nvim'
alias v='vim'
alias la='ls -a'
alias latr='ls -latr'


alias config='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'
